These are the common operations we perform in this notebook

01. tf.ones()
02. tf.eye()
03. tf.zeros()
04. tf.matmul()
05. tf.multiply()
06. tf.transpose()
07. tf.matrix_transpose()
08. tf.fill()
09. tf.eval()
10. tf.diag()
11. tf.range()
12. tf.random_normal()
13. tf.random_uniform()
14. tf.squeeze()
15. tf.expand_dims()
16. tf.reshape()
17. tf.get_shape()
19. tf.add()
20. tf.constant() and more ...


In [1]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

In [2]:
tf.InteractiveSession() #Invoking this statement within IPython will make Tensorflow behave almost imperatively.
                        # Its like we are using numPy
a = tf.zeros([2,2])

In [5]:
a = tf.zeros(2)
a
# It return the reference to the desired tensor rather than the value of
# the tensor itself.

<tf.Tensor 'zeros_3:0' shape=(2,) dtype=float32>

In [6]:
tf.Tensor.eval(a) # it return python object

array([0., 0.], dtype=float32)

In [7]:
a.eval()  # we can also use this bcz tensorflow run in interactive shell right now

array([0., 0.], dtype=float32)

In [10]:
a = tf.zeros(shape=[2,3,2])
a.eval()

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [11]:
b = tf.ones([3,3,1])
b.eval()

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)

In [16]:
b = tf.fill((2,2),value = 10)
b.eval()

array([[10, 10],
       [10, 10]])

In [18]:
tf.random_normal(shape=[2,2]).eval()

array([[ 2.0319288 , -0.21603112],
       [-0.5260285 , -1.3883319 ]], dtype=float32)

In [20]:
tf.random_normal([5,3],mean=5,stddev=10).eval()

array([[-6.2988615 ,  7.887633  , -4.322589  ],
       [15.864253  ,  9.183531  , -0.9506502 ],
       [ 7.0398893 , 17.52123   ,  4.0934677 ],
       [-3.127903  , -0.17396355,  3.513902  ],
       [-0.9351177 ,  0.10905552, 11.813223  ]], dtype=float32)

In [21]:
tf.random_uniform([5,3],minval=0,maxval=1).eval()

array([[0.11130273, 0.93233883, 0.18002534],
       [0.40021813, 0.7515366 , 0.10502613],
       [0.32220924, 0.5454725 , 0.53354406],
       [0.7899302 , 0.21318913, 0.05187619],
       [0.59300923, 0.5694536 , 0.9739362 ]], dtype=float32)

## Adding and Scaling

In [25]:
a = tf.ones(shape=(2,2))
b = tf.ones(shape=[2,2])
(a+b).eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [29]:
((a+b)*2).eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [31]:
tf.matmul(a,b).eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [35]:
c = tf.fill((2,2),20)
d = tf.fill([2,2],10)
(c*d).eval()

array([[200, 200],
       [200, 200]])

In [36]:
tf.eye(4).eval() # create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [37]:
tf.range(10).eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
tf.diag(tf.range(10)).eval()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [72]:
tf.random_normal((4,2),seed=42).eval()

array([[-0.28077507, -0.1377521 ],
       [-0.6763296 ,  0.02458041],
       [-0.89358455, -0.82847327],
       [ 1.2068944 ,  1.3810157 ]], dtype=float32)

In [102]:
a = tf.random_normal((4,2),seed=42)
tf.transpose(a).eval()

array([[-0.28077507, -0.6763296 , -0.89358455,  1.2068944 ],
       [-0.1377521 ,  0.02458041, -0.82847327,  1.3810157 ]],
      dtype=float32)

In [103]:
b = tf.random_normal((4,2),seed=42)
tf.matrix_transpose(a).eval()

array([[-0.13857655,  0.83471936, -2.317276  ,  1.2227972 ],
       [ 0.47280023, -0.3172532 , -0.20728105,  0.9955407 ]],
      dtype=float32)

In [104]:
print(a.shape,b.shape)

(4, 2) (4, 2)


In [106]:
tf.matmul(a,b,transpose_b=True).eval() # dot product

array([[ 0.02240512,  0.13152455, -0.01357666,  0.07536395],
       [-0.05215753, -0.09887292, -0.19528711,  0.28343865],
       [-0.3017077 , -0.8799609 , -0.7925203 ,  0.9577391 ],
       [-0.27243137, -0.19612932, -1.3706014 ,  2.1894808 ]],
      dtype=float32)

In [107]:
tf.multiply(a,b).eval() # element vise multiplication

array([[-0.05119591, -0.03072143],
       [ 0.87999076, -0.29386908],
       [-1.0460699 , -0.13553706],
       [ 0.01207323, -0.75390047]], dtype=float32)

### Tensor types

In [120]:
z = tf.fill((2,2),'om').eval()
z

array([[b'om', b'om'],
       [b'om', b'om']], dtype=object)

In [123]:
a = tf.ones((2,2))
a.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [125]:
tf.to_int32(a).eval()

array([[1, 1],
       [1, 1]])

### Shape manipulation

In [137]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [139]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [141]:
a = tf.reshape(a,shape=[4]).eval()

In [151]:
print(a)
a.shape

[1. 1. 1. 1.]


(4,)

In [153]:
b = tf.expand_dims(a,axis=0).eval()
print(b)
b.shape

[[1. 1. 1. 1.]]


(1, 4)

In [161]:
c = tf.expand_dims(a,axis=1).eval()
print(c)
print(c.shape)

[[1.]
 [1.]
 [1.]
 [1.]]
(4, 1)


In [164]:
tf.squeeze(c).eval().shape # remove 1 dimensions

(4,)

### Broadcasting 

In [181]:
a = tf.ones((2,2))
b = tf.range(0,2,1,dtype=tf.float32)
(a + b).eval()

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [182]:
tf.add(a,b).eval()

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [183]:
a = 3
b = 4
c = a + b
c

7

This program, when translated into machine code, instructs the machine to perform a primitive addition operation on two registers, one which contains 3, and the other which contains 4. The result is then 7. This style of programming is called **imperative** since programming tells the computer explicitly which actions to perform

An alternate style of programming is **declarative.** In a declarative system, a computer program is a high level description of the computation which is to be performed. It does not instruct the computer exactly how to perform the computation.Consider the Tensorflow equivalent of the program above.

In [187]:
a = tf.constant(3)
b = tf.constant(4)
c = tf.add(a,b)
print(c) # value of c isn't 7 it create a new tensor
c.eval()

Tensor("Add_22:0", shape=(), dtype=int32)


7

### Tensorflow Graphs
Any computation in Tensorflow represented as an instance of a `tf.Graph` object. Such as _graph_ consists of a set of instances of `tf.Tensor` objects and `tf.Operation` objects. We have covered `tf.Tensor` in some detail, but what are `tf.Operation` objects? We have already seen them over the some notebooks. A call to an operation like _tf.matmul_ creates a `tf.Operation` instance to mark the need to perform the matrix multiplication operation.

When a `tf.Graph` is not explicitly specified, Tensorflow adds _tensors_ and _operations_ to a hidden global `tf.Graph` instance. This instance can be fetched by tf.get_default_graph().

In [189]:
tf.get_default_graph()

It is possible to specify that Tensorflow operations be performed in graphs other than the default

### Tensorflow Sessions
In Tensorflow, a `tf.Session()` object stores the context under which a computation is performed. At the beginning of this notebook, we used `tf.InteractiveSession()` to set up an environment for all Tensorflow computations. This call created a **hidden global context** for all computations performed. We then used `tf.Tensor.eval()` to execute our declaratively specified computations. Underneath the hood, this call is evaluated in context of this hidden global `tf.Session.` It can be convenient (and often necessary) to use an explicit context for a computation instead of a hidden context.

In [192]:
ss = tf.Session()
a = tf.ones((3,3))
b = tf.matmul(a,a)
b.eval(session=ss)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

This code evaluates **b** in the context of **ss** instead of the hidden global session. In fact, we can make this more explicit with an alternate notation

In [208]:
ss.run(b)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [212]:
b.eval(),ss.run(b)

(array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=float32), array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=float32))

In [213]:
print(id(b.eval(session=ss)))  # both are different
print(id(ss.run(b)))            

1661811624976
1661811050576


In fact, calling `b.eval(session=ss)` is just syntactic sugar for calling `sess.run(b).`

This entire code may smack a bit of sophistry. What does it matter which session is in play given that all the different methods seem to return the same answer? 
**Explicit sessions don’t really show their value until we start to perform computations which have state**

### Tensorflow Variables

The `tf.Variable()` class provides a wrapper around tensors which allows for stateful computations. The variable objects serve as holders for tensors. Creating a variable is easy enough.

In [224]:
a = tf.Variable(tf.ones((2,2)))
a

<tf.Variable 'Variable_4:0' shape=(2, 2) dtype=float32_ref>

In [219]:
# What happens when we try to evaluate the variable 'a' as throught it were a tensor?
a.eval()

FailedPreconditionError: Attempting to use uninitialized value Variable_3
	 [[{{node _retval_Variable_3_0_0}}]]

The evaluation fails since variables have to be excplicitly initialized. The easiest way to initialize all variables is to invoke `tf.global_variables_initializer`. Running this operation within a session will initialize all variables in the program

In [226]:
ss = tf.Session()
ss.run(tf.global_variables_initializer())
ss.run(a)

array([[1., 1.],
       [1., 1.]], dtype=float32)

Variables only become interesting once we can assign to them. `tf.assign()` 

In [237]:
a.assign(tf.zeros((2,2),dtype=tf.float32)).eval() # This variable is initialized so 
                                                #we can access this through hidden context

array([[0., 0.],
       [0., 0.]], dtype=float32)